### ISSUE TITLE
frog server stops running in Docker image

### ISSUE THREAD

**Issue by Gijs-Koot** [proycon/LaMachine#4] opened 2016-01-26 12:56 UTC
After building the docker image, starting the frog server doesn't work because after booting the server stops immediately with error message `Killed`. I didn't kill the frog though. 

```
[root@413e5da503d2 LaMachine]# frog -S 40000
frog 0.13.1 (c) CLTS, ILK 1998 - 2016
[...]
frog-parser-:initiating parser ...
frog-parser-:reading /etc/frog//Frog.mbdp.1.0.pairs.sampled.ibase
frog-parser-:reading /etc/frog//Frog.mbdp.1.0.dir.ibase
Killed
[root@413e5da503d2 LaMachine]#
```

Using `frog`, for example through the python bindings, works fine.

**Comment by Gijs-Koot** [comment] 2016-01-26 13:44
Somehow, after rebuilding, I got a bit further, the server is now starting. But it's then failing to fork on an incoming request, leading to an exit. 

```
frog-server_1 | frog-:Initialization done.
frog-server_1 | frog-:Listening on port 8080
frog-server_1 | frog-:New connection...
frog-server_1 | frog-:ERROR on fork
frog-server_1 | frog-:Server error:FORK failed Exiting.
frog-server_1 | frog-:fatal error: FORK failed
frogdocker_frog-server_1 exited with code 1
```

**Comment by proycon** [comment] 2016-01-26 16:29
Thanks for the feedback, we were indeed about to suggest you try again after we patched frog with some more verbose error output and we rebuild the docker image, and it seems you already did so :)

I'm not sure what causes this error, it seems to be fairly docker specific as we can't reproduce it standalone, I will try to see if I can get it to reproduce it with docker.

**Comment by proycon** [comment] 2016-01-26 17:09
How did you run the docker image? If I do it as follows then everything works as it should. I can't seem to replicate the issue yet.

Running an interactive instance with a mapped port, and a Frog server:

    host$ docker run -p 12345:12345 -t -i proycon/lamachine
    [root@521f680bbfc2 LaMachine]# frog -S 12345

Connecting to the Frog server from the host:

    host$ telnet localhost 12345
    Trying ::1...
    Connected to localhost.
    Escape character is '^]'.
    Dit is een test.
    EOT
    1       Dit     dit     [dit]   VNW(aanw,pron,stan,vol,3o,ev)   0.777085        O       B-NP    2       su
    2       is      zijn    [zijn]  WW(pv,tgw,ev)   0.999891        O       B-VP    0       ROOT
    3       een     een     [een]   LID(onbep,stan,agr)     0.999113        O       B-NP    4       det
    4       test    test    [test]  N(soort,ev,basis,zijd,stan)     0.903055        O       I-NP    2       predc
    5       .       .       [.]     LET()   1.000000        O       O       4       punct

**Comment by Gijs-Koot** [comment] 2016-01-27 12:05
I've tried again, following exactly your suggestions, and I still get the `failed on fork` error. See complete log below. I didn't mention it earlier, but I'm running this on

```
Mac OS X El Capitan 10.11.2
docker-machine version 0.4.1 (e2c88d6)
docker version 1.8.3, build f4bf5c7
```

Here's the complete error log. As a workaround, I'm building a simple server that wraps the python library. 

```
frog-docker  docker run -p 12345:12345 -t -i proycon/lamachine
[root@8042e8d29fbf LaMachine]# frog -S 12345
frog 0.13.1 (c) CLTS, ILK 1998 - 2016
CLST  - Centre for Language and Speech Technology,Radboud University
ILK   - Induction of Linguistic Knowledge Research Group,Tilburg University
based on [ucto 0.8.3, libfolia 0.14, timbl 6.4.8, ticcutils 0.12, mbt 3.2.16]
frog-:config read from: /etc/frog/frog.cfg
frog-tok-:Initiating tokeniser...
frog-pos-tagger-mbt-:  Reading the lexicon from: /etc/frog/Frog.mbt.1.0.lex.ambi.05 (229170 words).
frog-pos-tagger-mbt-:  Read frequent words list from: /etc/frog/Frog.mbt.1.0.top500 (500 words).
frog-pos-tagger-mbt-:  Reading case-base for known words from: /etc/frog/Frog.mbt.1.0.known.dddwfWawa...
frog-pos-tagger-mbt-:  case-base for known words read.
frog-pos-tagger-mbt-:  Reading case-base for unknown words from: /etc/frog/Frog.mbt.1.0.unknown.chnppdddwFawasss...
frog-pos-tagger-mbt-:  case-base for unknown word read
frog-pos-tagger-mbt-:  Sentence delimiter set to '<utt>'
frog-pos-tagger-mbt-:  Beam size = 1
frog-pos-tagger-mbt-:  Known Tree, Algorithm = IGTREE
frog-pos-tagger-mbt-:  Unknown Tree, Algorithm = IB1
frog-pos-tagger-mbt-:
frog-iob-mbt-:  Reading the lexicon from: /etc/frog/chunker.train.lex.ambi.05 (78570 words).
frog-iob-mbt-:  Read frequent words list from: /etc/frog/chunker.train.top1000 (1000 words).
frog-iob-mbt-:  Reading case-base for known words from: /etc/frog/chunker.train.known.dddwfWawa...
frog-iob-mbt-:  case-base for known words read.
frog-iob-mbt-:  Reading case-base for unknown words from: /etc/frog/chunker.train.unknown.chnppddwFawsss...
frog-iob-mbt-:  case-base for unknown word read
frog-iob-mbt-:  Sentence delimiter set to '<utt>'
frog-iob-mbt-:  Beam size = 1
frog-iob-mbt-:  Known Tree, Algorithm = IGTREE
frog-iob-mbt-:  Unknown Tree, Algorithm = IB1
frog-iob-mbt-:
frog-ner-mbt-:  Reading the lexicon from: /etc/frog/ner.data.lex.ambi.05 (73735 words).
frog-ner-mbt-:  Read frequent words list from: /etc/frog/ner.data.top1000 (1000 words).
frog-ner-mbt-:  Reading case-base for known words from: /etc/frog/ner.data.known.ddwdwfWawawaa...
frog-ner-mbt-:  case-base for known words read.
frog-ner-mbt-:  Reading case-base for unknown words from: /etc/frog/ner.data.unknown.chnppddwdwFawawaasss...
frog-ner-mbt-:  case-base for unknown word read
frog-ner-mbt-:  Sentence delimiter set to 'EL'
frog-ner-mbt-:  Beam size = 1
frog-ner-mbt-:  Known Tree, Algorithm = IGTREE
frog-ner-mbt-:  Unknown Tree, Algorithm = TRIBL
frog-ner-mbt-:
frog-mblem:Initiating lemmatizer...
frog-mbma-:Initiating morphological analyzer...
frog-mwu-:initiating mwuChunker...
frog-mwu-:read mwus /etc/frog//Frog.mwu.1.0
frog-parser-:initiating parser ...
frog-parser-:reading /etc/frog//Frog.mbdp.1.0.pairs.sampled.ibase
frog-parser-:reading /etc/frog//Frog.mbdp.1.0.dir.ibase
frog-parser-:reading /etc/frog//Frog.mbdp.1.0.rels.ibase
frog-:Initialization done.
frog-:Listening on port 12345
frog-:New connection...
frog-:ERROR on fork
frog-:Server error:FORK failed Exiting.
frog-:fatal error: FORK failed
```

**Comment by proycon** [comment] 2016-01-27 13:29
Is this the latest LaMachine image now? We added some more debug output that should include more information on why the fork failed, although I don't know how insightful that will prove yet. 

I notice you're running docker on Mac OS X, which in turn uses a Linux VM. Is it possible the VM is just running out of memory or somehow has no multithreading support? That might explain the error.

(You can optionally also use LaMachine as a VM directly by the way)

**Comment by Gijs-Koot** [comment] 2016-01-27 13:32
This is the workaround: https://github.com/Gijs-Koot/frog-docker-flask-gunicorn. I'll check the new logging output.

**Comment by Gijs-Koot** [comment] 2016-01-27 13:49
Yes, it's running out of memory, or at least, it cannot allocate it. It is a limited VM so this makes sense. It does run with two `gunicorn` workers as a python library though, as in the setup I posted earlier.   

```
[...]
frog-:Listening on port 12345
frog-:New connection...
frog-:ERROR on fork: Cannot allocate memory
frog-:Server error:FORK failed: Cannot allocate memory Exiting.
```

For now, I'm going to go with the workaround.

**Comment by proycon** [comment] 2016-01-27 13:52
Ok, that explains the error then. Nice workaround indeed! I'll close the issue for now then.

**Closed by proycon** 2016-01-27 13:52 UTC

**Comment by megasnort** [comment] 2016-09-16 10:03
To whom it may concern: I had a similar problem (Frog was _Killed_ while starting) and was able to solve this problem myself by bumping the memory of my VM a bit (I was using the same configuration as Gijs: OSX -> Linux VM -> Docker)

In `Vagrantfile`:

```
config.vm.provider "virtualbox" do |vb|
  vb.memory = "4096"
end
```

**Comment by proycon** [comment] 2016-09-20 21:01
Thanks for the tip!
