### ISSUE TITLE
python-frog doesn't install on proycon/lamachine image

### ISSUE THREAD

**Issue by Gijs-Koot** [proycon/LaMachine#8] opened 2016-03-23 14:03 UTC
On the docker image, `python-frog` is not yet installed (could be usefull to include), and it doesn't install either: 

with `pip install python-frog`:

```
[...]
Error compiling Cython file:
    ------------------------------------------------------------
    ...
            pass



    cdef class Document:
        cdef frog_classes.Document capi
            ^
    ------------------------------------------------------------

    frog_wrapper.pyx:34:9: 'Document' is not a type identifier
    building 'frog' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/root/local/include/ -I/usr/include/ -I/usr/include/libxml2 -I/usr/local/include/ -I/usr/include/python3.5m -c frog_wrapper.cpp -o build/temp.linux-x86_64-3.5/frog_wrapper.o --std=c++0x
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    frog_wrapper.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
     #error Do not use this file, it is the result of a failed Cython compilation.
      ^
    error: command 'gcc' failed with exit status 1
```

from source:

```
[...]
frog_wrapper.cpp:364:36: note: in definition of macro ‘__Pyx_PyBool_FromLong’
     #define __Pyx_PyBool_FromLong(b) ((b) ? __Pyx_NewRef(Py_True) : __Pyx_NewRef(Py_False))
                                        ^
    frog_wrapper.cpp: In function ‘int __pyx_pf_4frog_11FrogOptions_4__setitem__(__pyx_obj_4frog_FrogOptions*, PyObject*, PyObject*)’:
    frog_wrapper.cpp:2220:24: error: ‘class FrogOptions’ has no member named ‘doDeepMorph’
         __pyx_v_self->capi.doDeepMorph = ((bool)__pyx_t_6);
                            ^
    error: command 'gcc' failed with exit status 1
```

**Comment by proycon** [comment] 2016-03-23 15:55
Thanks for the report! I see we indeed have some version conflicts between python-frog and frog currently in LaMachine (clashes between development and stable releases). I'll try to straighten it out!

**Comment by proycon** [comment] 2016-03-23 22:49
The issue is fixed now. The newly triggered docker build just completed successfully (it installed python-frog through pip). Everything should work again (just don't mix the stable release frog release with the development python-frog release or vice versa)

**Closed by proycon** 2016-03-23 22:49 UTC

**Comment by Gijs-Koot** [comment] 2016-03-24 10:26
Great, thanks!
