### ISSUE TITLE
bash script in WSL fails on step 'lamachine-cpp-automake : foliautils - Invoke make'

### ISSUE THREAD

**Issue by JJWTimmer** [proycon/LaMachine#157] opened 2019-08-29 19:10 UTC
Hi,
Building on Windows Subsystem for Linux (latest Ubuntu terminal) failed for me first time about virtualenv and after a manual install it failed on lamachine-cpp-automake : foliautils - Invoke make.

Error output:
```
TASK [lamachine-cpp-automake : foliautils - Invoke make] ********************************************************************************************************************************************************************************************************************************************
fatal: [jt-brain]: FAILED! => {"changed": true, "cmd": ["make"], "delta": "0:00:09.505250", "end": "2019-08-29 20:54:48.193773", "msg": "non-zero return code", "rc": 2, "start": "2019-08-29 20:54:38.688523", "stderr": "ar: `u' modifier ignored since `D' is the default (see `U')
FoLiA-stats.cxx: In function ‘std::vector<folia::FoliaElement*> gather_nodes(const folia::Document*, const string&, const std::set<std::__cxx11::basic_string<char> >&, const std::set<std::__cxx11::basic_string<char> >&)’:
FoLiA-stats.cxx:1106:71: error: no matching function for call to ‘folia::FoliaElement::select(const folia::ElementType&, std::set<folia::ElementType>&, bool)’
     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );
                                                                       ^
In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,
                 from FoLiA-stats.cxx:42:
/home/jasper/frog/include/libfolia/folia_impl.h:156:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(const string&, const std::set<folia::ElementType>&, bool) const
       std::vector<F*> select( const std::string& st,
                       ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:156:23: note:   template argument deduction/substitution failed:
FoLiA-stats.cxx:1106:71: note:   couldn't deduce template parameter ‘F’
     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );
                                                                       ^
In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,
                 from FoLiA-stats.cxx:42:
/home/jasper/frog/include/libfolia/folia_impl.h:172:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(const string&, bool) const
       std::vector<F*> select( const std::string& st,
                       ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:172:23: note:   template argument deduction/substitution failed:
FoLiA-stats.cxx:1106:71: note:   candidate expects 2 arguments, 3 provided
     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );
                                                                       ^
In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,
                 from FoLiA-stats.cxx:42:
/home/jasper/frog/include/libfolia/folia_impl.h:186:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(const char*, bool) const
       std::vector<F*> select( const char* st,
                       ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:186:23: note:   template argument deduction/substitution failed:
FoLiA-stats.cxx:1106:71: note:   candidate expects 2 arguments, 3 provided
     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );
                                                                       ^
In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,
                 from FoLiA-stats.cxx:42:
/home/jasper/frog/include/libfolia/folia_impl.h:200:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(const std::set<folia::ElementType>&, bool) const
       std::vector<F*> select( const std::set<ElementType>& exclude,
                       ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:200:23: note:   template argument deduction/substitution failed:
FoLiA-stats.cxx:1106:71: note:   candidate expects 2 arguments, 3 provided
     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );
                                                                       ^
In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,
                 from FoLiA-stats.cxx:42:
/home/jasper/frog/include/libfolia/folia_impl.h:214:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(bool) const
       std::vector<F*> select( bool recurse = true ) const {
                       ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:214:23: note:   template argument deduction/substitution failed:
FoLiA-stats.cxx:1106:71: note:   candidate expects 1 argument, 3 provided
     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );
                                                                       ^
In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,
                 from FoLiA-stats.cxx:42:
/home/jasper/frog/include/libfolia/folia_impl.h:487:40: note: candidate: virtual std::vector<folia::FoliaElement*> folia::FoliaElement::select(folia::ElementType, folia::SELECT_FLAGS) const
     virtual std::vector<FoliaElement*> select( ElementType elementtype,
                                        ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:487:40: note:   candidate expects 2 arguments, 3 provided
/home/jasper/frog/include/libfolia/folia_impl.h:489:40: note: candidate: virtual std::vector<folia::FoliaElement*> folia::FoliaElement::select(folia::ElementType, const std::set<folia::ElementType>&, folia::SELECT_FLAGS) const
     virtual std::vector<FoliaElement*> select( ElementType elementtype,
                                        ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:489:40: note:   no known conversion for argument 3 from ‘bool’ to ‘folia::SELECT_FLAGS’
/home/jasper/frog/include/libfolia/folia_impl.h:492:40: note: candidate: virtual std::vector<folia::FoliaElement*> folia::FoliaElement::select(folia::ElementType, const string&, folia::SELECT_FLAGS) const
     virtual std::vector<FoliaElement*> select( ElementType elementtype,
                                        ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:492:40: note:   no known conversion for argument 2 from ‘std::set<folia::ElementType>’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’
/home/jasper/frog/include/libfolia/folia_impl.h:495:40: note: candidate: virtual std::vector<folia::FoliaElement*> folia::FoliaElement::select(folia::ElementType, const string&, const std::set<folia::ElementType>&, folia::SELECT_FLAGS) const
     virtual std::vector<FoliaElement*> select( ElementType elementtype,
                                        ^~~~~~
/home/jasper/frog/include/libfolia/folia_impl.h:495:40: note:   no known conversion for argument 2 from ‘std::set<folia::ElementType>’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’
make[2]: *** [FoLiA-stats.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2", "stderr_lines": ["ar: `u' modifier ignored since `D' is the default (see `U')", "FoLiA-stats.cxx: In function ‘std::vector<folia::FoliaElement*> gather_nodes(const folia::Document*, const string&, const std::set<std::__cxx11::basic_string<char> >&, const std::set<std::__cxx11::basic_string<char> >&)’:", "FoLiA-stats.cxx:1106:71: error: no matching function for call to ‘folia::FoliaElement::select(const folia::ElementType&, std::set<folia::ElementType>&, bool)’", "     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );", "                                                                       ^", "In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,", "                 from FoLiA-stats.cxx:42:", "/home/jasper/frog/include/libfolia/folia_impl.h:156:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(const string&, const std::set<folia::ElementType>&, bool) const", "       std::vector<F*> select( const std::string& st,", "                       ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:156:23: note:   template argument deduction/substitution failed:", "FoLiA-stats.cxx:1106:71: note:   couldn't deduce template parameter ‘F’", "     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );", "                                                                       ^", "In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,", "                 from FoLiA-stats.cxx:42:", "/home/jasper/frog/include/libfolia/folia_impl.h:172:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(const string&, bool) const", "       std::vector<F*> select( const std::string& st,", "                       ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:172:23: note:   template argument deduction/substitution failed:", "FoLiA-stats.cxx:1106:71: note:   candidate expects 2 arguments, 3 provided", "     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );", "                                                                       ^", "In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,", "                 from FoLiA-stats.cxx:42:", "/home/jasper/frog/include/libfolia/folia_impl.h:186:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(const char*, bool) const", "       std::vector<F*> select( const char* st,", "                       ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:186:23: note:   template argument deduction/substitution failed:", "FoLiA-stats.cxx:1106:71: note:   candidate expects 2 arguments, 3 provided", "     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );", "                                                                       ^", "In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,", "                 from FoLiA-stats.cxx:42:", "/home/jasper/frog/include/libfolia/folia_impl.h:200:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(const std::set<folia::ElementType>&, bool) const", "       std::vector<F*> select( const std::set<ElementType>& exclude,", "                       ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:200:23: note:   template argument deduction/substitution failed:", "FoLiA-stats.cxx:1106:71: note:   candidate expects 2 arguments, 3 provided", "     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );", "                                                                       ^", "In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,", "                 from FoLiA-stats.cxx:42:", "/home/jasper/frog/include/libfolia/folia_impl.h:214:23: note: candidate: template<class F> std::vector<F*> folia::FoliaElement::select(bool) const", "       std::vector<F*> select( bool recurse = true ) const {", "                       ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:214:23: note:   template argument deduction/substitution failed:", "FoLiA-stats.cxx:1106:71: note:   candidate expects 1 argument, 3 provided", "     vector<FoliaElement*> v = doc->doc()->select( tag, skiptags, true );", "                                                                       ^", "In file included from /home/jasper/frog/include/libfolia/folia.h:31:0,", "                 from FoLiA-stats.cxx:42:", "/home/jasper/frog/include/libfolia/folia_impl.h:487:40: note: candidate: virtual std::vector<folia::FoliaElement*> folia::FoliaElement::select(folia::ElementType, folia::SELECT_FLAGS) const", "     virtual std::vector<FoliaElement*> select( ElementType elementtype,", "                                        ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:487:40: note:   candidate expects 2 arguments, 3 provided", "/home/jasper/frog/include/libfolia/folia_impl.h:489:40: note: candidate: virtual std::vector<folia::FoliaElement*> folia::FoliaElement::select(folia::ElementType, const std::set<folia::ElementType>&, folia::SELECT_FLAGS) const", "     virtual std::vector<FoliaElement*> select( ElementType elementtype,", "                                        ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:489:40: note:   no known conversion for argument 3 from ‘bool’ to ‘folia::SELECT_FLAGS’", "/home/jasper/frog/include/libfolia/folia_impl.h:492:40: note: candidate: virtual std::vector<folia::FoliaElement*> folia::FoliaElement::select(folia::ElementType, const string&, folia::SELECT_FLAGS) const", "     virtual std::vector<FoliaElement*> select( ElementType elementtype,", "                                        ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:492:40: note:   no known conversion for argument 2 from ‘std::set<folia::ElementType>’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’", "/home/jasper/frog/include/libfolia/folia_impl.h:495:40: note: candidate: virtual std::vector<folia::FoliaElement*> folia::FoliaElement::select(folia::ElementType, const string&, const std::set<folia::ElementType>&, folia::SELECT_FLAGS) const", "     virtual std::vector<FoliaElement*> select( ElementType elementtype,", "                                        ^~~~~~", "/home/jasper/frog/include/libfolia/folia_impl.h:495:40: note:   no known conversion for argument 2 from ‘std::set<folia::ElementType>’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’", "make[2]: *** [FoLiA-stats.o] Error 1", "make[1]: *** [all-recursive] Error 1", "make: *** [all] Error 2"], "stdout": "make  all-recursive
make[1]: Entering directory '/home/jasper/frog/src/foliautils'
Making all in src
make[2]: Entering directory '/home/jasper/frog/src/foliautils/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I ../include/  -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include  -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/  -I/usr/include/libxml2 -MT common_code.lo -MD -MP -MF .deps/common_code.Tpo -c -o common_code.lo common_code.cxx
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I ../include/ -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/ -I/usr/include/libxml2 -MT common_code.lo -MD -MP -MF .deps/common_code.Tpo -c common_code.cxx  -fPIC -DPIC -o .libs/common_code.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I ../include/ -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/ -I/usr/include/libxml2 -MT common_code.lo -MD -MP -MF .deps/common_code.Tpo -c common_code.cxx -o common_code.o >/dev/null 2>&1
mv -f .deps/common_code.Tpo .deps/common_code.Plo
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include  -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/  -I/usr/include/libxml2 -version-info 1:0:0  -o libfoliautils.la -rpath /home/jasper/frog/lib common_code.lo  -L/home/jasper/frog/lib -lfolia -L/home/jasper/frog/lib -lucto -L/home/jasper/frog/lib -lticcutils -lxml2 -licuio -licui18n -licuuc -licudata -lexttextcat-2.0 
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/7/crtoffloadbegin.o  .libs/common_code.o   -Wl,-rpath -Wl,/home/jasper/frog/lib -Wl,-rpath -Wl,/home/jasper/frog/lib -L/home/jasper/frog/lib /home/jasper/frog/lib/libfolia.so /home/jasper/frog/lib/libucto.so /home/jasper/frog/lib/libticcutils.so -lxml2 -licuio -licui18n -licuuc -licudata -lexttextcat-2.0 -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. -lstdc++ -lm -lgomp -lpthread -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o /usr/lib/gcc/x86_64-linux-gnu/7/crtoffloadend.o  -g -fopenmp -fopenmp   -fopenmp -pthread -Wl,-soname -Wl,libfoliautils.so.1 -o .libs/libfoliautils.so.1.0.0
libtool: link: (cd \".libs\" && rm -f \"libfoliautils.so.1\" && ln -s \"libfoliautils.so.1.0.0\" \"libfoliautils.so.1\")
libtool: link: (cd \".libs\" && rm -f \"libfoliautils.so\" && ln -s \"libfoliautils.so.1.0.0\" \"libfoliautils.so\")
libtool: link: ar cru .libs/libfoliautils.a  common_code.o
libtool: link: ranlib .libs/libfoliautils.a
libtool: link: ( cd \".libs\" && rm -f \"libfoliautils.la\" && ln -s \"../libfoliautils.la\" \"libfoliautils.la\" )
g++ -DHAVE_CONFIG_H -I. -I..  -I ../include/  -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include  -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/  -I/usr/include/libxml2 -MT FoLiA-stats.o -MD -MP -MF .deps/FoLiA-stats.Tpo -c -o FoLiA-stats.o FoLiA-stats.cxx
Makefile:824: recipe for target 'FoLiA-stats.o' failed
make[2]: Leaving directory '/home/jasper/frog/src/foliautils/src'
Makefile:420: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/jasper/frog/src/foliautils'
Makefile:352: recipe for target 'all' failed", "stdout_lines": ["make  all-recursive", "make[1]: Entering directory '/home/jasper/frog/src/foliautils'", "Making all in src", "make[2]: Entering directory '/home/jasper/frog/src/foliautils/src'", "/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I ../include/  -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include  -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/  -I/usr/include/libxml2 -MT common_code.lo -MD -MP -MF .deps/common_code.Tpo -c -o common_code.lo common_code.cxx", "libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I ../include/ -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/ -I/usr/include/libxml2 -MT common_code.lo -MD -MP -MF .deps/common_code.Tpo -c common_code.cxx  -fPIC -DPIC -o .libs/common_code.o", "libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I ../include/ -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/ -I/usr/include/libxml2 -MT common_code.lo -MD -MP -MF .deps/common_code.Tpo -c common_code.cxx -o common_code.o >/dev/null 2>&1", "mv -f .deps/common_code.Tpo .deps/common_code.Plo", "/bin/bash ../libtool  --tag=CXX   --mode=link g++ -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include  -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/  -I/usr/include/libxml2 -version-info 1:0:0  -o libfoliautils.la -rpath /home/jasper/frog/lib common_code.lo  -L/home/jasper/frog/lib -lfolia -L/home/jasper/frog/lib -lucto -L/home/jasper/frog/lib -lticcutils -lxml2 -licuio -licui18n -licuuc -licudata -lexttextcat-2.0 ", "libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/7/crtoffloadbegin.o  .libs/common_code.o   -Wl,-rpath -Wl,/home/jasper/frog/lib -Wl,-rpath -Wl,/home/jasper/frog/lib -L/home/jasper/frog/lib /home/jasper/frog/lib/libfolia.so /home/jasper/frog/lib/libucto.so /home/jasper/frog/lib/libticcutils.so -lxml2 -licuio -licui18n -licuuc -licudata -lexttextcat-2.0 -L/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/7/../../.. -lstdc++ -lm -lgomp -lpthread -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/7/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crtn.o /usr/lib/gcc/x86_64-linux-gnu/7/crtoffloadend.o  -g -fopenmp -fopenmp   -fopenmp -pthread -Wl,-soname -Wl,libfoliautils.so.1 -o .libs/libfoliautils.so.1.0.0", "libtool: link: (cd \".libs\" && rm -f \"libfoliautils.so.1\" && ln -s \"libfoliautils.so.1.0.0\" \"libfoliautils.so.1\")", "libtool: link: (cd \".libs\" && rm -f \"libfoliautils.so\" && ln -s \"libfoliautils.so.1.0.0\" \"libfoliautils.so\")", "libtool: link: ar cru .libs/libfoliautils.a  common_code.o", "libtool: link: ranlib .libs/libfoliautils.a", "libtool: link: ( cd \".libs\" && rm -f \"libfoliautils.la\" && ln -s \"../libfoliautils.la\" \"libfoliautils.la\" )", "g++ -DHAVE_CONFIG_H -I. -I..  -I ../include/  -std=c++11 -W -Wall -pedantic -g -I/home/jasper/frog/include -I/usr/include/libxml2 -I/home/jasper/frog/include -fopenmp -I/home/jasper/frog/include  -D U_USING_ICU_NAMESPACE=1 -fopenmp -I/usr/include/libexttextcat/  -I/usr/include/libxml2 -MT FoLiA-stats.o -MD -MP -MF .deps/FoLiA-stats.Tpo -c -o FoLiA-stats.o FoLiA-stats.cxx", "Makefile:824: recipe for target 'FoLiA-stats.o' failed", "make[2]: Leaving directory '/home/jasper/frog/src/foliautils/src'", "Makefile:420: recipe for target 'all-recursive' failed", "make[1]: Leaving directory '/home/jasper/frog/src/foliautils'", "Makefile:352: recipe for target 'all' failed"]}
```

**Comment by proycon** [comment] 2019-08-30 09:47
> Building on Windows Subsystem for Linux (latest Ubuntu terminal) failed for me first time about virtualenv

Hmm, that's not supposed to happen.  What did it say? What Ubuntu version were you running, if you say latest you mean 19.04?

> and after a manual install it failed on lamachine-cpp-automake : foliautils - Invoke make.

We did happen to do some new releases yesterday. So far our tests look okay, but I'll investigate to see if anything went wrong.

**Comment by proycon** [comment] 2019-08-30 10:20
Okay, the problem now replicates across all builds and was probably caused by yesterday's new releases, currently causing all LaMachine builds to fail.

@kosloot I suspect foliautils was not properly released along with the rest and the old stable is not compatible with the new libfolia?

**Comment by kosloot** [comment] 2019-08-30 14:43
Well, I thought is was ...
a new version is released an now all seem happy

**Comment by proycon** [comment] 2019-09-01 15:56
The problem should be fixed now

**Closed by proycon** 2019-09-01 15:56 UTC
Labels: PRIORITY, bug, investigate
